FROM node:22-alpine AS builder

WORKDIR /app
ENV NODE_PATH=/app:/app/dist

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build


FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/generated ./generated

EXPOSE 2000

CMD ["sh", "-c", "npx prisma db push && node dist/src/main.js"]
