events {}

http {

    server {

        listen 80;

        server_name test.kitepkura.edu.kg.;


        location / {

            proxy_pass http://frontend:3000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }

    }


    server {

        listen 80;

        server_name api.kitepkura.edu.kg.;


        location / {

            proxy_pass http://backend:2000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }

    }

}