events {}

http {

    # HTTP -> HTTPS для основного домена
    server {
        listen 80;
        server_name kitepkura.edu.kg;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://www.kitepkura.edu.kg/admin;
        }
    }


    # HTTP -> HTTPS для www
    server {
        listen 80;
        server_name www.kitepkura.edu.kg;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://www.kitepkura.edu.kg$request_uri;
        }
    }


    # HTTP -> HTTPS для API
    server {
        listen 80;
        server_name api.kitepkura.edu.kg;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://api.kitepkura.edu.kg$request_uri;
        }
    }


    # HTTPS основной сайт
    server {
        listen 443 ssl;
        server_name www.kitepkura.edu.kg;

        ssl_certificate /etc/letsencrypt/live/kitepkura.edu.kg/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kitepkura.edu.kg/privkey.pem;


        location / {
            proxy_pass http://frontend:3000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }


    # HTTPS редирект без www
    server {
        listen 443 ssl;
        server_name kitepkura.edu.kg;

        ssl_certificate /etc/letsencrypt/live/kitepkura.edu.kg/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kitepkura.edu.kg/privkey.pem;

        return 301 https://www.kitepkura.edu.kg/admin;
    }


    # HTTPS API
    server {
        listen 443 ssl;
        server_name api.kitepkura.edu.kg;

        ssl_certificate /etc/letsencrypt/live/kitepkura.edu.kg/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kitepkura.edu.kg/privkey.pem;


        location / {
            proxy_pass http://backend:2000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}